type = "fluxmonitor"
schemaVersion = 1
name = "ETHUSD Feed"
externalJobID = "6ed8591e-c6b7-430c-804d-b775ea6511f9"
maxTaskDuration = "0s"
threshold = 0.5
contractAddress = "0x84b3eC007A986DCDd356D7b503A19B30329Fe56d"
idleTimerPeriod = "1h"
idleTimerDisabled = false
pollTimerPeriod = "1m0s"
pollTimerDisabled = false
observationSource = """
    // data source 1
    ds1 [type="http" method=GET url="https://ethusd-example.fly.dev/"]
    ds1_parse [type="jsonparse" path="data,price"]

    // data source 2
    ds2 [type="http" method=GET url="https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum"]
    ds2_parse [type="jsonparse" path="0,current_price"]

    ds1 -> ds1_parse -> medianized_answer
    ds2 -> ds2_parse -> medianized_answer

    medianized_answer [type=median]
"""